# Travis CI for automatic building.
#
# Changelog:
#  - 2019-01-29: deployment of pages with travis
#  - 2019-01-28: deployment of releases with travis
#  - 2019-01-07: handling bioconductor
#  - 2018-12-08: coverage updated
#  - 2018-09-12: added check for OS X
#  - 2018-09-11: warning as error set to false
#  - 2018-06-29: first try

language: r

r_check_args: --as-cran

env:
  - PKG_TARBALL=PLNmodels_0.8.1.gz

sudo: required

cache: packages

warnings_are_errors: false

addons:
  apt:
    packages:
    - libnlopt-dev

brew_packages:
  - gcc
  - nlopt

r_packages:
  - covr

use_bioc: true
bioc_required: true

bioc_packages:
  - biomformat
  - phyloseq

matrix:
  include:
    - os: linux
      r: bioc-release
      after_success:
      - Rscript -e 'covr::codecov()'
      deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: ${PKG_TARBALL}
          skip_cleanup: true
          on:
            tags: true
        - provider: pages
          github-token: $GITHUB_TOKEN
          script: Rscript -e 'pkgdown::deploy_site_github()'
          skip_cleanup: true
          local_dir: "docs"
          keep-history: true
          on:
            branch: master
    - os: linux
      r: bioc-devel
    - os: osx
      r: bioc-release

